---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    post:
      summary: Creates an user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                user_name:
                  type: string
                password:
                  type: string
              required:
              - user_name
              - password
          application/xml:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                user_name:
                  type: string
                password:
                  type: string
              required:
              - user_name
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
